import type { MetricDefinition, SubscoreKey } from "./types";
import { pct, ratioX, num, years, ppt, phrase } from "./formatters";

export const DIVIDEND_METRICS: MetricDefinition[] = [
  {
    key: "dividendYield",
    label: "Rentabilidad por dividendo",
    extract: (c) => c.dividendYield,
    higherIsBetter: true,
    weight: 0.18,
    format: pct,
    describe: phrase("Rentabilidad por dividendo", "atractiva", "reducida"),
  },
  {
    key: "payoutRatioEarnings",
    label: "Payout sobre beneficio",
    extract: (c) => c.payoutRatioEarnings,
    higherIsBetter: false,
    sweetSpot: { low: 0.3, high: 0.7 },
    weight: 0.15,
    format: pct,
    describe: phrase("Payout sobre beneficio", "en un rango sano", "fuera de un rango sano"),
  },
  {
    key: "payoutRatioFCF",
    label: "Payout sobre flujo de caja libre",
    extract: (c) => c.payoutRatioFCF,
    higherIsBetter: false,
    sweetSpot: { low: 0.3, high: 0.75 },
    weight: 0.15,
    format: pct,
    describe: phrase("Payout sobre caja libre", "en un rango sano", "fuera de un rango sano"),
  },
  {
    key: "consecutiveYearsPaying",
    label: "Años consecutivos pagando dividendo",
    extract: (c) => c.consecutiveYearsPaying,
    higherIsBetter: true,
    weight: 0.12,
    format: years,
    describe: phrase("Historial de pago de dividendo", "largo", "corto"),
  },
  {
    key: "consecutiveYearsIncreasing",
    label: "Años consecutivos aumentando dividendo",
    extract: (c) => c.consecutiveYearsIncreasing,
    higherIsBetter: true,
    weight: 0.18,
    format: years,
    describe: phrase("Racha de subidas del dividendo", "consistente", "poco consistente"),
  },
  {
    key: "dividendCagr5y",
    label: "Crecimiento del dividendo (5 años)",
    extract: (c) => c.dividendCagr5y ?? c.dividendCagr3y,
    higherIsBetter: true,
    weight: 0.12,
    format: pct,
    describe: phrase("Crecimiento anualizado del dividendo", "sólido", "débil"),
  },
  {
    key: "dividendCoverage",
    label: "Cobertura del dividendo (caja libre / dividendos)",
    extract: (c) => c.dividendCoverage,
    higherIsBetter: true,
    weight: 0.1,
    format: ratioX,
    describe: phrase("Cobertura del dividendo con caja libre", "holgada", "ajustada"),
  },
];

export const GROWTH_METRICS: MetricDefinition[] = [
  {
    key: "revenueGrowthCagr3y",
    label: "Crecimiento de ingresos (3 años)",
    extract: (c) => c.revenueGrowthCagr3y,
    higherIsBetter: true,
    weight: 0.15,
    format: pct,
    describe: phrase("Crecimiento de ingresos a 3 años", "sólido", "débil"),
  },
  {
    key: "revenueGrowthCagr5y",
    label: "Crecimiento de ingresos (5 años)",
    extract: (c) => c.revenueGrowthCagr5y,
    higherIsBetter: true,
    weight: 0.2,
    format: pct,
    describe: phrase("Crecimiento de ingresos a 5 años", "sostenido", "débil"),
  },
  {
    key: "epsGrowthCagr3y",
    label: "Crecimiento del BPA (3 años)",
    extract: (c) => c.epsGrowthCagr3y,
    higherIsBetter: true,
    weight: 0.2,
    format: pct,
    describe: phrase("Crecimiento del beneficio por acción a 3 años", "fuerte", "débil"),
  },
  {
    key: "epsGrowthCagr5y",
    label: "Crecimiento del BPA (5 años)",
    extract: (c) => c.epsGrowthCagr5y,
    higherIsBetter: true,
    weight: 0.2,
    format: pct,
    describe: phrase("Crecimiento del beneficio por acción a 5 años", "fuerte", "débil"),
  },
  {
    key: "fcfGrowthCagr3y",
    label: "Crecimiento del flujo de caja libre (3 años)",
    extract: (c) => c.fcfGrowthCagr3y,
    higherIsBetter: true,
    weight: 0.15,
    format: pct,
    describe: phrase("Crecimiento del flujo de caja libre", "sólido", "débil"),
  },
  {
    key: "operatingMarginTrend5y",
    label: "Evolución del margen operativo (5 años)",
    extract: (c) => c.operatingMarginTrend5y,
    higherIsBetter: true,
    weight: 0.1,
    format: ppt,
    describe: phrase("Evolución del margen operativo", "en expansión", "en contracción"),
  },
];

export const QUALITY_METRICS: MetricDefinition[] = [
  {
    key: "roic",
    label: "ROIC",
    extract: (c) => c.roic,
    higherIsBetter: true,
    weight: 0.2,
    format: pct,
    describe: phrase("ROIC (retorno sobre el capital invertido)", "elevado", "reducido"),
  },
  {
    key: "roe",
    label: "ROE",
    extract: (c) => c.roe,
    higherIsBetter: true,
    weight: 0.15,
    format: pct,
    describe: phrase("ROE (retorno sobre el capital propio)", "elevado", "reducido"),
  },
  {
    key: "operatingMargin",
    label: "Margen operativo",
    extract: (c) => c.operatingMargin,
    higherIsBetter: true,
    sectorRelative: true,
    weight: 0.15,
    format: pct,
    describe: phrase("Margen operativo", "amplio para su sector", "estrecho para su sector"),
  },
  {
    key: "netMargin",
    label: "Margen neto",
    extract: (c) => c.netMargin,
    higherIsBetter: true,
    sectorRelative: true,
    weight: 0.1,
    format: pct,
    describe: phrase("Margen neto", "amplio para su sector", "estrecho para su sector"),
  },
  {
    key: "earningsStability",
    label: "Estabilidad de beneficios",
    extract: (c) => c.earningsStability,
    higherIsBetter: true,
    weight: 0.15,
    format: pct,
    describe: phrase("Estabilidad histórica de beneficios", "alta", "baja"),
  },
  {
    key: "netDebtToEbitda",
    label: "Deuda neta / EBITDA",
    extract: (c) => c.netDebtToEbitda,
    higherIsBetter: false,
    weight: 0.15,
    format: ratioX,
    describe: phrase("Deuda neta sobre EBITDA", "controlada", "elevada"),
  },
  {
    key: "interestCoverage",
    label: "Cobertura de intereses",
    extract: (c) => c.interestCoverage,
    higherIsBetter: true,
    weight: 0.1,
    format: ratioX,
    describe: phrase("Cobertura de intereses de la deuda", "amplia", "ajustada"),
  },
];

export const VALUATION_METRICS: MetricDefinition[] = [
  {
    key: "per",
    label: "PER",
    extract: (c) => c.per,
    higherIsBetter: false,
    sectorRelative: true,
    weight: 0.2,
    format: ratioX,
    describe: phrase("PER frente a su sector", "atractivo", "exigente"),
  },
  {
    key: "forwardPer",
    label: "PER estimado (forward)",
    extract: (c) => c.forwardPer,
    higherIsBetter: false,
    sectorRelative: true,
    weight: 0.15,
    format: ratioX,
    describe: phrase("PER estimado frente a su sector", "atractivo", "exigente"),
  },
  {
    key: "peg",
    label: "PEG",
    extract: (c) => c.peg,
    higherIsBetter: false,
    sweetSpot: { low: 0, high: 1.5 },
    weight: 0.15,
    format: num,
    describe: phrase("PEG (precio ajustado a su crecimiento)", "razonable", "exigente"),
  },
  {
    key: "evEbitda",
    label: "EV/EBITDA",
    extract: (c) => c.evEbitda,
    higherIsBetter: false,
    sectorRelative: true,
    weight: 0.2,
    format: ratioX,
    describe: phrase("EV/EBITDA frente a su sector", "atractivo", "exigente"),
  },
  {
    key: "priceToFcf",
    label: "Precio / flujo de caja libre",
    extract: (c) => c.priceToFcf,
    higherIsBetter: false,
    sectorRelative: true,
    weight: 0.2,
    format: ratioX,
    describe: phrase("Precio sobre caja libre frente a su sector", "atractivo", "exigente"),
  },
  {
    key: "perVsHistoricalAvg5y",
    label: "PER actual vs. media histórica (5 años)",
    extract: (c) => c.perVsHistoricalAvg5y,
    higherIsBetter: false,
    weight: 0.1,
    format: (v) => `${(v * 100).toFixed(0)}% de su media 5 años`,
    describe: phrase("Valoración frente a su propia media histórica", "por debajo", "por encima"),
  },
];

export const RISK_METRICS: MetricDefinition[] = [
  {
    key: "volatility3y",
    label: "Volatilidad (3 años)",
    extract: (c) => c.volatility3y,
    higherIsBetter: false,
    weight: 0.2,
    format: pct,
    describe: phrase("Volatilidad histórica", "contenida", "elevada"),
  },
  {
    key: "beta",
    label: "Beta",
    extract: (c) => c.beta,
    higherIsBetter: false,
    weight: 0.15,
    format: num,
    describe: phrase("Sensibilidad al mercado (beta)", "moderada", "alta"),
  },
  {
    key: "maxDrawdown5y",
    label: "Máxima caída (5 años)",
    extract: (c) => c.maxDrawdown5y,
    higherIsBetter: false,
    weight: 0.2,
    format: pct,
    describe: phrase("Máxima caída histórica", "contenida", "pronunciada"),
  },
  {
    key: "netDebtToEbitdaRisk",
    label: "Apalancamiento (deuda neta / EBITDA)",
    extract: (c) => c.netDebtToEbitda,
    higherIsBetter: false,
    weight: 0.15,
    format: ratioX,
    describe: phrase("Nivel de apalancamiento", "controlado", "elevado"),
  },
  {
    key: "earningsStabilityRisk",
    label: "Estabilidad de beneficios",
    extract: (c) => c.earningsStability,
    higherIsBetter: true,
    weight: 0.15,
    format: pct,
    describe: phrase("Estabilidad de beneficios", "alta", "baja"),
  },
  {
    key: "marketCapSize",
    label: "Tamaño (capitalización)",
    extract: (c) => c.marketCapUSD,
    higherIsBetter: true,
    weight: 0.15,
    format: (v) => `$${(v / 1_000_000_000).toFixed(0)} mil M`,
    describe: phrase("Tamaño de la compañía", "grande y más resiliente", "reducido y más sensible a shocks"),
  },
];

export const MOMENTUM_METRICS: MetricDefinition[] = [
  {
    key: "return6m",
    label: "Rentabilidad 6 meses",
    extract: (c) => c.return6m,
    higherIsBetter: true,
    weight: 0.2,
    format: pct,
    describe: phrase("Rentabilidad de los últimos 6 meses", "positiva", "negativa"),
  },
  {
    key: "return1y",
    label: "Rentabilidad 1 año",
    extract: (c) => c.return1y,
    higherIsBetter: true,
    weight: 0.25,
    format: pct,
    describe: phrase("Rentabilidad del último año", "positiva", "negativa"),
  },
  {
    key: "return3yCagr",
    label: "Rentabilidad anualizada 3 años",
    extract: (c) => c.return3yCagr,
    higherIsBetter: true,
    weight: 0.2,
    format: pct,
    describe: phrase("Rentabilidad anualizada a 3 años", "positiva", "negativa"),
  },
  {
    key: "distanceFromHigh52w",
    label: "Distancia respecto a máximos de 52 semanas",
    extract: (c) => c.distanceFromHigh52w,
    higherIsBetter: false,
    weight: 0.2,
    format: pct,
    describe: phrase("Distancia respecto a máximos de 52 semanas", "reducida", "amplia"),
  },
  {
    key: "aboveSma200",
    label: "Tendencia (precio vs. media de 200 sesiones)",
    extract: (c) => (c.aboveSma200 ? 1 : 0),
    higherIsBetter: true,
    weight: 0.15,
    format: (v) => (v === 1 ? "por encima de su media de 200 sesiones" : "por debajo de su media de 200 sesiones"),
    describe: (formatted) => `Tendencia de precio ${formatted}`,
  },
];

export const METRICS_BY_SUBSCORE: Record<SubscoreKey, MetricDefinition[]> = {
  dividend: DIVIDEND_METRICS,
  growth: GROWTH_METRICS,
  quality: QUALITY_METRICS,
  valuation: VALUATION_METRICS,
  risk: RISK_METRICS,
  momentum: MOMENTUM_METRICS,
};
